// Action Types
export const IS_LOADING = "IS_LOADING";
export const CHANGE_NAME_SUCCESS = "CHANGE_NAME_SUCCESS";
export const GET_MAP_SUCCESS = "GET_MAP_SUCCESS";
export const MOVEMENT_SUCCESS = "MOVEMENT_SUCCESS";
export const SHRINE_PATH_SUCCESS = "SHRINE_PATH_SUCCESS";
export const STATUS_SUCCESS = "STATUS_SUCCESS";
export const PRAY_SUCCESS = "PRAY_SUCCESS";
export const PICKUP_SUCCESS = "PICKUP_SUCCESS";
export const EXAMINE_SUCCESS = "EXAMINE_SUCCESS";
